---
- hosts:
# - localhost
  - samba









  gather_facts: true
  remote_user: root

  tasks:

  - name: update package cache
    tags:
    - base
    apt: update_cache=yes

#  - name: upgrade installed packages
#    tags:
#    - upgrade
#    apt: upgrade=full

  - name: install base packages
    tags:
    - base
    action: apt pkg={{ item }} state=latest
    with_items:
      - apt
      - aptitude
      - etcsic
      - parted
      - htop
      - atop
      - atop-nolog
      - multitail
      - molly-guard
      - byobu
      - mc
      - lsof
      - git
      - reptyr
      - ethtool
      - strace
      - ohai

  - name: create config dirs
    tags:
    - base
    - config
    file: dest={{ item }} state=directory
    with_items:
      - ~/.config/mc
      - ~/.byobu

  - name: use preconfigured mc config
    tags:
    - base
    - config
    copy:
      src=resources/mc/ini
      dest=~/.config/mc/ini
      mode=640
      owner=root
      group=root

  - name: use preconfigured byobu config
    tags:
    - base
    - config
    unarchive:
      src=resources/byobu/byobu.tgz
      dest=~/

  - name: add sshb script
    tags:
    - base
    - binary
    template:
      src=resources/byobu/sshb
      dest=/usr/local/bin/sshb
      mode=750
      owner=root
      group=root
