---
- hosts: 
  - localhost
  - rpi2
  remote_user: root
  vars:
    host: 0x201

  tasks:

  - name: add custom bash prompt
    lineinfile: 
      dest=~/.bashrc
      regexp="^PS1='\[\w+]"
      line="PS1='[***] \[\033[1;31m\]\u\[\033[0;0m\]@{{ host }}:\w\$ '"
      state=present
      backrefs=yes
      # insertafter='^PS1'
