---
- hosts: testservers
  remote_user: root

  tasks:

  - name: install byobu
    tags: byobu_pkg
    apt: 
      name=byobu
      state=latest 

  - name: create settings dir
    file:
      dest=~/.byobu 
      state=directory 

  - name: use preconfigured settings
    tags: byobu_config
    unarchive: 
      src=resources/byobu/byobu.tgz
      dest=~/

  - name: add sshb script
    tags: byobu_config
    file: 
      src=resources/byobu/sshb
      dest=/usr/local/bin/
      mode=750
      owner=root
      group=root
