---
- hosts: 

  - etcsic

  gather_facts: false
  remote_user: root

  vars:
    git_url: git@development.bcs.bcs
    git_repo: etcsic
    git_origin: "{{ git_url }}:{{ git_repo }}/{{ ansible_fqdn }}/.git"

  tasks:

  - name: ensure latest etcsic version
    tags: git_origin
    apt: update_cache=yes name=etcsic state=latest

  - stat: path=/etc/.git
    tags: git_origin
    register: return

  - name: use preconfigured git_config
    tags: git_origin
    template:
      src=resources/etcsic/config
      dest=/etc/.git/config
    when: return.stat.isdir is defined

- hosts: 

  - etcsic_legacy

  gather_facts: True
  remote_user: root

  vars:
    git_url: git@development.bcs.bcs
    git_repo: etcsic
    git_origin: "{{ git_url }}:{{ git_repo }}/{{ ansible_fqdn }}/.git"

  tasks:

  - name: ensure latest etcsic version
    tags: git_origin_legacy
    apt: update_cache=yes name=etcsic state=latest

  - stat: path=/etc/.git
    tags: git_origin_legacy
    register: return_legacy

  - name: use preconfigured git_config for legacy systems
    tags: git_origin_legacy
    template:
      src=resources/etcsic/config_legacy
      dest=/etc/.git/config
    when: return_legacy.stat.isdir is defined
    
#  - name: add remote origin to config
#    lineinfile: 
#      dest=/etc/.git/config
#      regexp="^logallrefudates"
#      line="PS1='[test] \[\033[1;31m\]\u\[\033[0;0m\]@{{ fqdn_host }}:\w\$ '"
#      state=present
#      backrefs=yes
#      insertafter='^PS1'
