---
- hosts: 
    - localhost
#   - testservers
#   - test
  remote_user: root

  tasks:

  - name: create root ssh folder
    file:
      dest=~/.ssh
      mode=700
      owner=root
      group=root

  - name: copy ssh user_keys
    tags: user_keys
    template:
      src=resources/ssh/user_keys
      dest=~/.ssh/authorized_keys
      mode=640
      owner=root
      group=root

  - name: copy ssh user_keys_priv
    tags: user_keys_priv
    template:
      src=resources/ssh/user_keys_priv
      dest=~/.ssh/authorized_keys
      mode=640
      owner=root
      group=root

  - name: copy ssh root_keys
    tags: root_keys
    template:
      src=resources/ssh/root_keys
      dest=~/.ssh/authorized_keys2
      mode=640
      owner=root
      group=root

- hosts:

    - git

  remote_user: root

  tasks:

  - name: add git keys
    tags: git_keys
    template:
      src=resources/ssh/git_keys
      dest=/media/development/git/.ssh/authorized_keys
      mode=640
      owner=git
      group=git
